### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by DigitalA1** [royboy789/Angular-Wordpress-Theme#19]
Hi Roy!

Noticed you added post_by_slug custom endpoint...thank you.

Is there a way to use filters like ?filter[taxonomy]=eats-categories&filter[term]=eats-video
on that custom endpoint?

Also, when we visit /wp-json/wp/v2/post_by_slug only 1 post comes up...?
if we put /wp-json/wp/v2/post_by_slug/_post_slug_here_ its 404

**Comment by royboy789** [comment]
if you have a slug, its a 1-1 relationship.. that is why it only returns back 1 post. There should only be 1 post with any given slug.

**Comment by dgitaldesignco** [comment]
Thanks Roy

Is there a way to use filters on this custom endpoint?

Btw if anything ima hit you up on CodeCalvary when I get a chance.

**Comment by austinthedeveloper** [comment]
This write-up I did might help you. I ended up throwing out the original factory and built a Post Service:

http://www.austinthedeveloper.com/#/post/writing-a-wordpress-rest-service

If I'm looking for one post, I'll just pass a query object into params based off the url and select the first in the array:

```
{
  slug: pageSlug || $stateParams.slug
};
```

If you want to filter by category slug, you could pass this object into the Post Service:
```
{
  'filter[category_name]': categorySlug || $stateParams.slug
};
```
By doing this method instead of the `categories` endpoint, I can have URL's that look like post/category/category-name instead of post/category/22

**Comment by royboy789** [comment]
@austinthedeveloper if you have a new service, want to create a PR with it? would love to have it added in
